dependencies:

  - name: mongodb
    version: ">=1.0.0"
    repository: file://../charts/mongodb
  - name: mysql
    version: ">=1.0.0"
    repository: file://../charts/mysql
  - name: elasticsearch
    version: ">=1.0.0"
    repository: file://../charts/elasticsearch

