dependencies:

  - name: memcached
    version: ">=1.0.0"
    repository: file://../charts/memcached
  - name: mongodb
    version: ">=1.0.0"
    repository: file://../charts/mongodb
  - name: mysql
    version: ">=1.0.0"
    repository: file://../charts/mysql
  - name: rabbitmq
    version: ">=1.0.0"
    repository: file://../charts/rabbitmq
  - name: elasticsearch
    version: ">=1.0.0"
    repository: file://../charts/elasticsearch

