# Default values for tutor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
---
image:
  repository: uvwild/tutor
  tag: 11.0.2
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

activateIngress: false
# activateHttps: true

ID: 99teYyxXGH1L7XSxo5e7Behw

certmanagerIssuer: letsencrypt

# Tutor configuration parameters
LMS_HOST: "www.edx.otcdemo.gardener.t-systems.net"
CMS_HOST: "studio.edx.otcdemo.gardener.t-systems.net"
PLATFORM_NAME: "Open Helm edX on OTC"
CONTACT_EMAIL: dr.uv.wildner.os@gmail.com
LANGUAGE_CODE: en

ANDROID_OAUTH2_SECRET: Xvk31SCnWo9essPwPfEEzgbi
OPENEDX_SECRET_KEY: k20aCxkxWrd7pqf7mZnbBdIf
SECRET_KEY: "k20aCxkxWrd7pqf7mZnbBdIf"


ACTIVATE_ELASTICSEARCH: true
ACTIVATE_MONGODB: true
ACTIVATE_MYSQL: true
ACTIVATE_RABBITMQ: true
ACTIVATE_HTTPS: false
ACTIVATE_NOTES: false
ACTIVATE_XQUEUE: false

DOCKER_IMAGE_OPENEDX: overhangio/openedx:11.0.3
DOCKER_IMAGE_FORUM: overhangio/openedx-forum:11.0.3
#DOCKER_IMAGE_NOTES: overhangio/openedx-notes:10.1.4
DOCKER_IMAGE_XQUEUE: overhangio/openedx-xqueue:11.0.0

DOCKER_IMAGE_ELASTICSEARCH: elasticsearch:1.5.2
DOCKER_IMAGE_MEMCACHED: memcached:1.5.2
DOCKER_IMAGE_MONGO: mongo:3.6.18
DOCKER_IMAGE_MYSQL: mysql:5.7.32
DOCKER_IMAGE_SMTP: namshi/smtp:latest
DOCKER_IMAGE_NGINX: nginx:1.13
DOCKER_IMAGE_RABBITMQ: rabbitmq:3.8.9-o-alpine

ELASTICSEARCH_HOST: "{{ .Release.Name }}-elasticsearch"
ELASTICSEARCH_PORT: 9200

FORUM_HOST: "{{ .Release.Name }}-forum"
FORUM_API_KEY: "forumapikey"

MEMCACHED_HOST: "{{ .Release.Name }}-memcached"
MEMCACHED_PORT: 11211

MONGODB_HOST: "{{ .Release.Name }}-mongodb"
MONGODB_DATABASE: "openedx"
MONGODB_PORT: 27017
MONGODB_USERNAME: "mongo"
MONGODB_PASSWORD: "mongo"

OPENEDX_MYSQL_DATABASE: openedx
OPENEDX_MYSQL_USERNAME: openedx
OPENEDX_MYSQL_PASSWORD: "ZKKT2d5J"

MYSQL_HOST: "{{ .Release.Name }}-mysql"
MYSQL_PORT: 3306
MYSQL_ROOT_USER: root
MYSQL_ROOT_PASSWORD: "skadeplJ"

NGINX_HTTP_PORT: 80
NGINX_LMS_UPSTREAM_HOST: '{{ include "tutor.fullname" . }}-lms'
NGINX_CMS_UPSTREAM_HOST: '{{ include "tutor.fullname" . }}-cms'
NGINX_NOTES_UPSTREAM_HOST: '{{ include "tutor.fullname" . }}-notes'

RABBITMQ_HOST: "{{ .Release.Name }}-rabbitmq"
RABBITMQ_USERNAME: ""
RABBITMQ_PASSWORD: ""

SMTP_HOST: "{{ .Release.Name }}-smtp"
SMTP_PORT: 25
SMTP_USERNAME: ""
SMTP_PASSWORD: ""

WEB_PROXY: false

XQUEUE_SECRET_KEY: ""
XQUEUE_AUTH_USERNAME: lms
XQUEUE_AUTH_PASSWORD: ""
XQUEUE_MYSQL_DATABASE: "xqueue"
XQUEUE_MYSQL_USERNAME: xqueue
XQUEUE_MYSQL_PASSWORD: ""


openedx:
  image:
    pullPolicy: IfNotPresent

lms:
  replicaCount: 1
  service:
    type: NodePort
    port: 8000

cms:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8000

forum:
  replicaCount: 1
  image:
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 4567

nginx:
  replicaCount: 1
  image:
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80

redis:
  replicaCount: 1
  image:
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 6379

mysql:
  generateSecret: false

workers:
  lms:
    replicaCount: 1
  cms:
    replicaCount: 1

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

tutorConfig: {}
