---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: caddy
  name: caddy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: caddy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: caddy
    spec:
      containers:
      - image: docker.io/caddy:2.2.1
        name: caddy
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - mountPath: /etc/caddy/
          name: config
        - mountPath: /data/
          name: data
      volumes:
      - configMap:
          name: {{ template "tutor.fullname" . }}-caddy-config
        name: config
      - name: data
        persistentVolumeClaim:
          claimName: {{ template "tutor.fullname" . }}-caddy-pvc

