---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: volume
    app.kubernetes.io/name: caddy
  name: {{ template "tutor.fullname" . }}-caddy-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

