apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tutor.fullname" . }}-nginx
  labels:
    app.kubernetes.io/component: nginx
    {{- include "tutor.common.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: nginx
      {{- include "tutor.common.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: nginx
        {{- include "tutor.common.labels" . | nindent 8 }}
      annotations:
        checksum/tutor-config: {{ include (print $.Template.BasePath "/tutor-configmap.yaml") . | sha256sum }}
    spec:
      volumes:
        - name: openedx-assets
          emptyDir: {}
        - name: tutor-config
          emptyDir: {}
        - name: nginx-config          
          configMap:
            defaultMode: 420
            name: {{ template "tutor.fullname" . }}-nginx-config
      initContainers:
        {{- include "tutor.config.container" . | nindent 8 }}
        - name: openedx-assets
          image: "{{ .Values.DOCKER_IMAGE_OPENEDX }}"
          imagePullPolicy: {{ .Values.openedx.image.pullPolicy }}
          command: ["cp", "-r", "/openedx/staticfiles/", "/var/www/openedx/"]
          volumeMounts:
            - name: openedx-assets
              mountPath: /var/www/openedx
      containers:
        - name: nginx
          image: "{{ .Values.DOCKER_IMAGE_NGINX }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: openedx-assets
              mountPath: /var/www/openedx
              readOnly: true
            - mountPath: /etc/nginx/conf.d/
              name: nginx-config
            # - name: tutor-config
            #   mountPath: /etc/nginx/conf.d/
            #   subPath: env/apps/nginx
            #   readOnly: true
