---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: redis
  name: redis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
    spec:
      containers:
      - image: docker.io/redis:6.0.9
        name: redis
        ports:
        - containerPort: {{ .Values.redis.service.port }}
        volumeMounts:
        - mountPath: /openedx/redis/config/
          name: config
        - mountPath: /openedx/redis/data
          name: data
      volumes:
      - configMap:
          name: {{ template "tutor.fullname" . }}-redis-config
        name: config
      - name: data
        persistentVolumeClaim:
          claimName: redis-pvc

