apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "tutor.fullname" . }}
data:
{{- range (keys .Values) -}}
{{- if eq . (. | snakecase | upper) -}}
{{- $value := tpl ((index $.Values .) | toString) $ -}}
{{ printf "TUTOR_%s: %s" . ($value | quote) | nindent 2 }}
{{- end -}}
{{- if eq . "JWT_RSA_PRIVATE_KEY" -}}
{{- $value := tpl ((index $.Values .) | toString) $ -}}
{{ printf "%s: %s" . ($value | quote) | nindent 2 }}
{{- end -}}
{{- end -}}
{{ printf "CMS_CFG: /openedx/config/cms.env.json" | nindent 2 }}
{{ printf "LMS_CFG: /openedx/config/lms.env.json" | nindent 2 }}
